---
extends: default

rules:
  line-length: disable
  truthy:
    allowed-values:
      - "true"
      - "false"
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
