---
- name: Configure mail server
  hosts: mail
  become: true
  gather_facts: true
  roles:
    - role: common
      tags: [common]
    - role: certbot
      tags: [certbot, tls]
    - role: mariadb
      tags: [mariadb, database]
    - role: dovecot
      tags: [dovecot]
    - role: rspamd
      tags: [rspamd]
    - role: postfix
      tags: [postfix]
