---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: mailserver
    box: debian/bookworm64
    memory: 1024
    groups:
      - mail
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    links:
      group_vars: ../../group_vars
  extra_vars:
    mail_letsencrypt_enabled: false
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
