---
- name: Configure Let's Encrypt certificates
  ansible.builtin.import_tasks: letsencrypt.yml
  when: mail_letsencrypt_enabled | bool

- name: Configure self-signed certificates
  ansible.builtin.import_tasks: selfsigned.yml
  when: not (mail_letsencrypt_enabled | bool)
