---
galaxy_info:
  role_name: postfix
  description: Postfix MTA with virtual mailboxes and Rspamd milter
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
dependencies: []
