---
mail_dovecot_packages:
  - dovecot-core
  - dovecot-imapd
  - dovecot-lmtpd
  - dovecot-mysql
  - dovecot-sieve
  - dovecot-managesieved
mail_dovecot_config_mode: "0644"
mail_dovecot_sql_mode: "0440"
mail_mysql_socket: /run/mysqld/mysqld.sock
